### ISSUE TITLE
Better cache verification, perhaps using RTC+TTL

### ISSUE THREAD

**Issue by jasiek** [londonhackspace/acnode-cl#48] opened 2016-05-12 23:12 UTC
Validity of cards in the cache is meant to be verified on startup (currently disabled). This takes ~3 sec per card, and at a few hundred cards introduces a long delay before making the tool operational. Instead of doing this, do the following:
- enable the RTC
- sync the RTC on startup and every 1 (?) day.
- when a card is scanned, look at the cache, see if the entry is older than a day, and if it is - check against the server.
- if the card is deemed to be invalid, remove from the cache, or mark as disabled.
- if the card is marked as disabled in the cache, ensure that there are no more than ~600 entries in the cache, when using EEPROM.

**Comment by zymurgic** [comment] 2019-04-05 07:33
cache verification is now done against all cards in the cache on a regular basis. At the moment, it's all cards, every 30 minutes or so. This is not currently a problem with load on the acserver. Looking at cache sizes, it won't be for a very long time.
If it does get to be a problem, we can look at only reverifying those that are due to expire in the next hour or so. Closing for now, since the problem is solved.

**Closed by zymurgic** 2019-04-05 07:33 UTC
Labels: enhancement
